Truth = (
    "temen/uang?",
    "nama lu ada artinya ga? kalo ada apa?",
    "cicak/kecoa",
    "barang pertama yg lu beliin buat ortu",
    "bandung/jogja?",
    "Apa satu hal yang kamu takuti?",
    "rank tertinggi pas sekolah?",
    "hukuman disekolah yang paling diinget",
    "kamu lebih mirip sama mama/papa?",
    "apa yg terlintas dipikiran lu pas liat cermin?",
    "musim favorit?",
    "paling engga bisa apa?",
    "suka makanan asin?",
    "sekarang lagi suka sama siapa?",
    "pernah kepleset didepan umum ga?",
    "bulan ini udah abis duit berapa?",
    "sejarah/geografi?",
    "worst moment in life",
    "pernah kekunci?",
    "paling suka hari apa?",
    "kalo nanti lo jadi orang tua, cara apa yg bakal lo pakai buat mendidik anak lo?",
    "lu tipe anak yg gimana kalo dikelas?",
    "baca buku/nonton film",
    "sakit hati/sakit gigi?",
    "pernah nginjek tai ga?",
    "sehari main hp berapa jam?",
    "pernah bolos pas sekolah?",
    "hidup 70th tapi hidup sederhana/hidup 30th tapi punya segalanya?",
    "pernah deket tapi ga jadian?",
    "dimarahin/dicuekin?",
    "jomblo/taken?",
    "pernah ga pup tapi ga disiram?",
    "pernah masuk got?",
)

Dare = (
    "ss lockscreen"
    "nyanyi dangdut keras keras",
    "ss history youtube",
    "desain ulang bendera indonesia kalo dijajah afrika",
    "Lakukan 100× Push-up",
    "ss belanja terakhir di marketplace",
    "ss chat terjorok sama sahabat",
    "ss isi chat terakhir yg dikirim",
    "pacaran sama salah satu lawan main lu selama 1 hari",
    "Ucapkan kata pertama yang muncul di pikiranmu",
    "thetering temen sejam",
    "ss saldo shopeepay/ovo/dana",
    "ss chat sama papa",
    "Makan satu sendok Merica",
    "last search google",
    "kirim foto masa kecil",
    "peragain adegan sinetron",
    "cara paling dramatis untuk bersin",
    "bikin story foto aib",
    "chat 1 orang yg belum pernah lu ajak ngomong",
    "ss chat pertama sama pacar",
    "upload foto pake filter aneh",
    "ss status wa",
    "ss semua aplikasi yang ada di hp",
    "ss aplikasi paling ga kepake",
    "traktir temen",
    "pake lipstick (cowo). pake pomade (cewe)",
    "berdiri satu kaki semenit",
    "jilat siku",
    "Posting foto terlama di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "chat temen pake capslock tiba tiba",
    "meluk kaki meja",
    "memeluk diri sendiri mesra",
    "baca ayat kursi",
    "ketawa keras banget",
    "Kirim foto terjelek.",
    "ss riwayat pencarian facebook Anda",
    "ss galeri.",
    "ss beranda telegram",
    "pap depan",
    "Ss kontak teratas whatsapp",
    "foto sekelas pas sma",
    "Kirim cover lagu favoritmu. 🎤",
    "foto peliharaan",
    "ss keranjang shopee/tokopedia",
    "ss chat sama mama",
    "Jadiin foto gebetanmu sebagai foto profil.",
    "ss likes vide di tiktok/instagram",
    "minta bulu kaki orang",
    "cium orang sebelah",
    "ss chat sama gebetan",
)
